import type { Href } from 'expo-router';

/**
 * Cast a path string to a typed `Href`.
 *
 * Expo Router's typed-routes definitions are regenerated by the Metro/export
 * pipeline, so a freshly added route may not yet appear in the generated union
 * during a type-check. This tiny helper keeps navigation type-safe at call
 * sites (it returns `Href`) without depending on when those types regenerate.
 */
export function route(path: string): Href {
  return path as Href;
}
